# Generated by Django 4.2.20 on 2026-09-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalRuntimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_url', models.CharField(blank=True, max_length=255, verbose_name='门户根地址')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '门户运行配置',
                'verbose_name_plural': '门户运行配置',
            },
        ),
    ]
