# Generated by Django 5.2.4 on 2026-02-22 14:20

import app01.models
import django.core.validators
import django.db.models.deletion
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTerm', models.CharField(default='2025-2026学年第一学期', max_length=30)),
                ('courseNumber', models.CharField(default='000000', max_length=30)),
                ('courseName', models.CharField(default='未命名课程', max_length=30)),
                ('classNumber', models.CharField(default='01', max_length=2)),
                ('teachers', models.CharField(default='未命名老师', max_length=30)),
                ('status', models.CharField(choices=[('Y', '开启'), ('N', '关闭')], default='Y', max_length=10, verbose_name='开设状态')),
            ],
            options={
                'verbose_name': '课程',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='未命名作业', max_length=100, verbose_name='标题')),
                ('content', models.TextField(default='请修改作业正文~', verbose_name='内容')),
                ('display', models.BooleanField(default=True, help_text='勾选表示显示作业', verbose_name='是否显示')),
                ('uploadFileType', models.CharField(default='*', max_length=30, verbose_name='上传类型')),
                ('deadline', models.DateField(default=app01.models.default_deadline, verbose_name='截止日期')),
                ('maxFiles', models.IntegerField(default=1, help_text='允许上传的附件数量（1~3）', verbose_name='最大附件数')),
                ('slot1Name', models.CharField(default='实验报告', max_length=50, verbose_name='附件槽1名称')),
                ('slot2Name', models.CharField(blank=True, default='', max_length=50, verbose_name='附件槽2名称')),
                ('slot3Name', models.CharField(blank=True, default='', max_length=50, verbose_name='附件槽3名称')),
                ('courseBelongTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '作业',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未知', max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=2, verbose_name='姓别')),
                ('type', models.CharField(choices=[('T', '老师'), ('S', '学生')], default='S', max_length=2, verbose_name='类型')),
                ('email', models.EmailField(blank=True, default='user@szu.edu.cn', error_messages={'invalid': '邮箱格式错误'}, max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, default='13000000000', max_length=11, validators=[django.core.validators.RegexValidator(message='手机号格式错误，需为11位数字（如13812345678）', regex=re.compile('^1[3-9]\\d{9}$'))], verbose_name='手机号')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '教学用户',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app01.task')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app01.userprofile')),
            ],
            options={
                'verbose_name': '提交记录',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(to='app01.userprofile'),
        ),
        migrations.CreateModel(
            name='HomeworkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(help_text='对应附件槽位 1/2/3', verbose_name='槽位')),
                ('filePath', models.CharField(default='', max_length=255, verbose_name='文件路径')),
                ('originalName', models.CharField(default='', max_length=200, verbose_name='原始文件名')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app01.homework')),
            ],
            options={
                'verbose_name': '提交文件',
                'constraints': [models.UniqueConstraint(fields=('homework', 'slot'), name='unique_homework_slot')],
            },
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('courseBelongTo', 'title'), name='unique_course_title'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('courseTerm', 'courseNumber', 'classNumber'), name='unique_term_number'),
        ),
    ]
