# Generated by Django 5.2.4 on 2025-08-03 00:31

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classNumber',
            field=models.CharField(default='01', max_length=2),
        ),
        migrations.AddField(
            model_name='course',
            name='courseTerm',
            field=models.CharField(default='2025-2026学年第一学期', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.CharField(default='未命名老师', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, default='user@szu.edu.cn', error_messages={'invalid': '邮箱格式错误'}, max_length=254, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='13000000000', max_length=11, validators=[django.core.validators.RegexValidator(message='手机号格式错误，需为11位数字（如13812345678）', regex=re.compile('^1[3-9]\\d{9}$'))], verbose_name='手机号'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('courseTerm', 'courseNumber', 'classNumber'), name='unique_term_number'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('courseBelongTo', 'title'), name='unique_course_title'),
        ),
    ]
