# Generated by Django 5.2.4 on 2026-02-22 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='homeworkfile',
            name='unique_homework_slot',
        ),
        migrations.RemoveField(
            model_name='homeworkfile',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='task',
            name='maxFiles',
        ),
        migrations.RemoveField(
            model_name='task',
            name='slot1Name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='slot1Type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='slot2Name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='slot2Type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='slot3Name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='slot3Type',
        ),
        migrations.AddField(
            model_name='task',
            name='fileType',
            field=models.CharField(default='*', help_text='如 .docx,.pdf,.zip 或 * 表示不限', max_length=50, verbose_name='允许的文件类型'),
        ),
        migrations.AlterField(
            model_name='homeworkfile',
            name='homework',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='app01.homework'),
        ),
    ]
