# Generated by Django 5.2.13 on 2026-04-26 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_remove_homeworkfile_unique_homework_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('filePath', models.CharField(default='', max_length=500, verbose_name='文件路径')),
                ('originalName', models.CharField(default='', max_length=200, verbose_name='原始文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('display', models.BooleanField(default=True, verbose_name='对学生显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_materials', to='app01.course', verbose_name='所属课程')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.userprofile', verbose_name='上传者')),
            ],
            options={
                'verbose_name': '参考资料',
                'ordering': ['-created_at'],
            },
        ),
    ]
