# Generated by Django 5.2.4 on 2025-08-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_course_classnumber_course_courseterm_course_teachers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='未命名作业', max_length=100),
        ),
    ]
