# Generated by Django 5.2.4 on 2025-08-07 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 16, 0, tzinfo=datetime.timezone.utc), verbose_name='截止时间'),
        ),
    ]
