# Generated by Django 5.2.13 on 2026-04-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_reference_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencematerial',
            options={'ordering': ['sort_order', '-created_at', 'id'], 'verbose_name': '参考资料'},
        ),
        migrations.AddField(
            model_name='referencematerial',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='数字越小越靠前；教师端可用上移/下移调整', verbose_name='排序'),
        ),
    ]
