# Generated by Django 5.2.13 on 2026-07-15 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_homework_timestamps_and_impersonation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F（不合格）')], max_length=2, verbose_name='等级')),
                ('comment', models.TextField(blank=True, default='', verbose_name='评语')),
                ('graded_at', models.DateTimeField(auto_now_add=True, verbose_name='首次批改时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('needs_regrade', models.BooleanField(default=False, help_text='学生在不合格(F)后重新提交时置 True，教师再次保存等级后清除', verbose_name='待重评')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_given', to=settings.AUTH_USER_MODEL, verbose_name='批改人')),
                ('homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='app01.homework', verbose_name='提交记录')),
            ],
            options={
                'verbose_name': '定性成绩',
            },
        ),
    ]
