# Generated by Django 5.2.4 on 2026-07-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_homework_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='enable_cover_autofill',
            field=models.BooleanField(default=False, verbose_name='下载时自动填封面'),
        ),
        migrations.AddField(
            model_name='task',
            name='enable_template_download',
            field=models.BooleanField(default=False, verbose_name='允许学生下载模板'),
        ),
        migrations.AddField(
            model_name='task',
            name='template_original_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='模板原始文件名'),
        ),
        migrations.AddField(
            model_name='task',
            name='template_path',
            field=models.CharField(blank=True, default='', help_text='相对 BASE_DIR，目录为 file/.../报告模板/<作业标题>/', max_length=500, verbose_name='报告模板路径'),
        ),
        migrations.AddField(
            model_name='task',
            name='template_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='模板上传时间'),
        ),
    ]
