# Generated by Django 5.2.4 on 2025-08-11 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(default='请修改作业正文~', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='task',
            name='courseBelongTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.course', verbose_name='所属课程'),
        ),
        migrations.AlterField(
            model_name='task',
            name='display',
            field=models.BooleanField(default=True, help_text='勾选表示显示作业', verbose_name='是否显示'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='未命名作业', max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='task',
            name='uploadFileType',
            field=models.CharField(default='*', max_length=30, verbose_name='上传类型'),
        ),
    ]
