# Generated by Django 5.2.4 on 2025-08-17 04:06

import app01.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_task_content_alter_task_coursebelongto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=app01.models.default_deadline, verbose_name='截止日期'),
        ),
    ]
