# Generated by Django 5.2.4 on 2026-07-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_task_report_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enable_report_cover_autofill',
            field=models.BooleanField(default=False, verbose_name='课程默认：自动填封面'),
        ),
        migrations.AddField(
            model_name='course',
            name='enable_report_template_download',
            field=models.BooleanField(default=False, verbose_name='课程默认：允许下载模板'),
        ),
        migrations.AddField(
            model_name='course',
            name='report_template_original_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='课程默认模板文件名'),
        ),
        migrations.AddField(
            model_name='course',
            name='report_template_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='课程默认报告模板路径'),
        ),
        migrations.AddField(
            model_name='course',
            name='report_template_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='课程默认模板上传时间'),
        ),
    ]
