# Generated by Django 5.2.4 on 2026-07-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_course_default_report_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='precheck_cover_mode',
            field=models.CharField(choices=[('block', '硬拦截'), ('warn', '仅警告')], default='block', max_length=10, verbose_name='默认封面预检失败策略'),
        ),
        migrations.AddField(
            model_name='course',
            name='precheck_master',
            field=models.CharField(choices=[('off', '关闭预检'), ('cover_default', '默认开启封面预检')], default='off', max_length=20, verbose_name='预检总开关'),
        ),
        migrations.AddField(
            model_name='task',
            name='precheck_fail_mode',
            field=models.CharField(choices=[('inherit', '继承课程'), ('block', '硬拦截'), ('warn', '仅警告')], default='inherit', max_length=10, verbose_name='预检失败策略'),
        ),
        migrations.AddField(
            model_name='task',
            name='precheck_mode',
            field=models.CharField(choices=[('inherit', '继承课程'), ('off', '关闭预检'), ('cover', '仅封面预检'), ('framework', '仅框架预检'), ('cover_and_framework', '封面+框架预检')], default='inherit', max_length=32, verbose_name='预检模式'),
        ),
        migrations.AddField(
            model_name='task',
            name='precheck_package_json',
            field=models.TextField(blank=True, default='', verbose_name='框架预检规则JSON'),
        ),
        migrations.AddField(
            model_name='task',
            name='precheck_package_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='框架预检包更新时间'),
        ),
        migrations.AddField(
            model_name='task',
            name='precheck_package_version',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='框架预检包版本'),
        ),
    ]
