# Generated by Django 5.2.4 on 2026-07-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_precheck_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='precheck_warn_active',
            field=models.BooleanField(default=False, verbose_name='预检警告中'),
        ),
        migrations.AddField(
            model_name='homework',
            name='precheck_warn_text',
            field=models.TextField(blank=True, default='', verbose_name='预检警告内容'),
        ),
        migrations.AddField(
            model_name='homework',
            name='precheck_warned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预检警告时间'),
        ),
    ]
